import {escapeHtml as e, number as n, pct, label} from './ui.js';
import {icon} from './icons.js';

const slotNames = {head:'Головные уборы',body:'Одежда',accessory:'Аксессуары',background:'Комнаты'};
const safeNumber = value => Number.isFinite(Number(value)) ? Number(value) : 0;
const goalName = goal => goal?.target_role ? `${goal.target_role} · ${goal.target_grade}` : 'Ваша следующая цель';
const itemName = item => item?.name || item?.title || 'Новая вещь';
const itemId = item => item?.id || '';
const branches = data => data?.tree?.branches || [];
const wardrobe = data => data?.wardrobe || [];
const selectedItem = (data,id) => wardrobe(data).find(item=>item.id===id) || null;
const ask = (question,{skill,event,small=false}={}) => `<button type="button" class="${small?'companion-prompt':'button secondary'}" data-action="companion-ask" data-question="${e(question)}" ${skill?`data-skill="${e(skill)}"`:''} ${event?`data-event="${e(event)}"`:''}>${small?'':icon('sparkles')}${e(question)}</button>`;
const strip = text => String(text || '').replace(/[\r\n]+/g,' ');
function progress(value,name){return `<div class="companion-progress" role="meter" aria-label="${e(name)}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${pct(value)??0}"><span style="width:${pct(value)??0}%"></span></div>`;}

/** Local, authored line drawings are item thumbnails; the character itself is a 3D renderer. */
export function wardrobeThumbnail(item,extra=''){
  const color=/^#[\da-f]{3,8}$/i.test(item?.style?.color||'')?item.style.color:'#00805f';
  const shapes={
    head:'<path d="M21 35c-1-17 8-23 19-23s20 6 19 23Z" fill="currentColor"/><path d="M21 34h37c7 0 9 4 7 8H20c-8 0-8-8 1-8Z" fill="currentColor"/><path d="M40 13v21" stroke="white" stroke-opacity=".5" stroke-width="2"/>',
    body:'<path d="m26 17 14 6 14-6 15 14-12 12-5-5v27H28V38l-5 5-12-12Z" fill="currentColor"/><path d="M31 19c1 10 17 10 18 0M40 28v34" fill="none" stroke="white" stroke-opacity=".55" stroke-width="2"/><circle cx="45" cy="38" r="2" fill="white" fill-opacity=".8"/>',
    accessory:'<path d="M26 28v-6c0-14 28-14 28 0v6" fill="none" stroke="currentColor" stroke-width="6"/><rect x="19" y="25" width="42" height="41" rx="12" fill="currentColor"/><rect x="25" y="43" width="30" height="17" rx="6" fill="white" fill-opacity=".25"/><path d="M32 32h16" stroke="white" stroke-opacity=".6" stroke-width="3"/>',
    background:'<rect x="12" y="12" width="56" height="56" rx="9" fill="currentColor"/><path d="M12 53h56M45 12v41" stroke="white" stroke-width="2" stroke-opacity=".45"/><path d="M24 53V28h13v25M22 28h17M52 53V37h10v16" stroke="white" stroke-width="2.5" stroke-opacity=".7" fill="none"/>'
  };
  const specific={cap_starter:'<circle cx="40" cy="31" r="16" stroke="currentColor" stroke-width="4"/><path d="M17 67c0-23 46-23 46 0" stroke="currentColor" stroke-width="4"/><path d="M35 34h.01M45 34h.01" stroke="currentColor" stroke-width="5" stroke-linecap="round"/>',accessory_none:'<circle cx="40" cy="40" r="23" stroke="currentColor" stroke-width="4"/><path d="m24 56 32-32" stroke="currentColor" stroke-width="4"/>',accessory_notebook:'<rect x="22" y="12" width="39" height="57" rx="5" fill="currentColor"/><path d="M29 13v55M36 28h16M36 38h16M36 48h10" stroke="white" stroke-opacity=".6" stroke-width="2"/><path d="M20 23h7M20 36h7M20 49h7M20 61h7" stroke="currentColor" stroke-width="3"/>',accessory_compass:'<circle cx="40" cy="43" r="24" fill="currentColor"/><circle cx="40" cy="43" r="18" fill="white" fill-opacity=".75"/><path d="m43 27 3 20-9 12-3-20Z" fill="currentColor"/><path d="M34 18v-7h12v7" stroke="currentColor" stroke-width="4"/>',cap_quest:'<path d="M19 48c0-44 42-44 42 0Z" fill="currentColor"/><rect x="16" y="45" width="48" height="14" rx="5" fill="currentColor"/><path d="M24 46v10M32 46v10M40 46v10M48 46v10M56 46v10" stroke="white" stroke-opacity=".45" stroke-width="2"/><circle cx="40" cy="14" r="7" fill="currentColor"/>'};
  return `<svg class="wardrobe-thumbnail ${e(extra)}" viewBox="0 0 80 80" fill="none" style="color:${color}" aria-hidden="true">${specific[item?.id]||shapes[item?.slot]||shapes.accessory}</svg>`;
}

function stageView(data,{previewItem=null,compact=false}={}){
  const item=selectedItem(data,previewItem),next=data?.next_unlock;
  const welcome=next?`Ближайшее открытие — «${itemName(next)}». Давайте найдём шаг, который развивает нужный вам навык.`:'Я рядом, чтобы связывать ваши шаги с большой целью. Что хотите освоить?';
  return `<section class="companion-room ${compact?'companion-room-compact':''}" aria-label="Мастерская спутника">
    <div class="companion-room-top"><div class="companion-name"><span class="companion-online" aria-hidden="true"></span><strong>Ваш спутник</strong></div><span class="companion-level">${data?.enabled?`Уровень ${n(data.level||1)}`:'В вашем темпе'}</span></div>
    <div class="mascot-speech" id="mascot-speech" aria-live="polite" aria-atomic="true"><p id="mascot-speech-text">${e(welcome)}</p><small id="mascot-speech-source">Спутник · готов помочь</small></div>
    <div class="companion-stage" data-mascot-stage data-state="idle" ${item?`data-preview-item="${e(item.id)}"`:''} aria-label="3D-спутник в вашей комнате"><div class="mascot-loading" role="status"><span class="mascot-loading-orbit" aria-hidden="true"></span><p>Готовим вашу мастерскую…</p></div></div>
    ${item?`<div class="companion-fitting-note">${icon('eye')} <span>Примерка: <strong>${e(itemName(item))}</strong>${item.unlocked?'':' · ещё не открыто'}</span></div>`:''}
    <div class="companion-room-tools"><button class="companion-room-tool" data-action="companion-tab" data-id="wardrobe">${icon('briefcase')} Переодеть</button><button class="companion-room-tool" data-action="companion-tab" data-id="tree">${icon('skills')} Мои навыки</button></div>
    <p class="companion-model-note" data-mascot-model-note>Модель спутника появится после подключения</p>
  </section>`;
}

function nextActivity(data,profile){
  const recs=profile?.recommendations?.recommendations||profile?.recommendations?.items||[];
  const candidates=branches(data).flatMap(branch=>(branch.activities||[]).map(activity=>({...activity,skill_id:branch.skill_id,skill_name:branch.name,required:branch.required})));
  for(const rec of recs){const found=candidates.find(activity=>activity.event_id===rec.event_id);if(found)return found;}
  return candidates.sort((a,b)=>Number(b.critical)-Number(a.critical)||safeNumber(b.gap_closed)-safeNumber(a.gap_closed))[0]||null;
}

function learningPath(data,profile){
  const event=nextActivity(data,profile),goal=data.tree?.goal||profile?.goal;
  if(!event)return `<section class="companion-next-step"><h2>${data.tree?.coverage_pct===100?'Требования цели покрыты. Что дальше?':'У каждого роста есть маршрут'}</h2><p>${!goal?'Выберите карьерную цель — и спутник поможет связать с ней навыки и активности.':'Сейчас нет доступной активности с приростом навыка. Можно изучить дерево или изменить цель.'}</p><button class="button secondary" data-action="goal">${goal?'Посмотреть цель':'Выбрать цель'} ${icon('target')}</button></section>`;
  return `<section class="companion-next-step"><div class="companion-section-head"><h2>Следующий шаг</h2><span>${n(event.duration_hours)} ч</span></div><div class="companion-learning-path"><div class="companion-path-stop"><span class="companion-path-symbol">${icon('book')}</span><div><span>Активность</span><h3>${e(event.title)}</h3></div></div><div class="companion-path-stop"><span class="companion-path-symbol">${icon('skills')}</span><div><span>Навык</span><strong>${e(event.skill_name)} <b>${n(event.before)} → ${n(event.after)}</b></strong></div></div><div class="companion-path-stop"><span class="companion-path-symbol">${icon('target')}</span><div><span>Ведёт к цели</span><strong>${e(goalName(goal))}</strong></div></div></div><div class="companion-path-actions"><button class="button" data-action="event" data-id="${e(event.event_id)}">Открыть активность ${icon('arrow')}</button>${ask('Зачем мне эта активность?',{event:event.event_id,skill:event.skill_id})}</div></section>`;
}

function nextReward(data){
  const next=data.next_unlock;
  if(!next)return `<div class="companion-next-reward all-open">${icon('check-circle')}<div><strong>Весь гардероб открыт</strong><p>Новые навыки продолжают расти вместе с вами.</p></div><button class="text-button" data-action="companion-tab" data-id="wardrobe">Переодеться ${icon('arrow')}</button></div>`;
  const requirement=next.requirement||{},percent=requirement.target>0?safeNumber(requirement.current)/requirement.target*100:0;
  return `<div class="companion-next-reward">${wardrobeThumbnail(next)}<div><span>Следующее открытие</span><strong>${e(itemName(next))}</strong><p>${e(requirement.label||next.description)}</p>${progress(percent,'Прогресс открытия '+itemName(next))}</div><button class="icon-button" data-action="wardrobe-preview" data-id="${e(next.id)}" aria-label="Примерить ${e(itemName(next))}">${icon('eye')}</button></div>`;
}

/** Root may replace this island with its streaming chat view without changing the room. */
export function companionChatView(){
  return `<section class="companion-chat" id="companion-chat" aria-label="Разговор со спутником"><div class="companion-section-head"><h2>Давайте разберёмся</h2>${icon('sparkles')}</div><div id="chat-messages" class="companion-chat-messages" role="log" aria-live="polite" aria-label="Сообщения"><p class="companion-chat-welcome">Расскажите своими словами, что хотите уметь или что пока не получается.</p></div><div class="companion-prompts">${ask('Какой навык развивать дальше?',{small:true})}${ask('Что я открою после курса?',{small:true})}</div><form id="companion-chat-form" class="companion-chat-form"><label class="sr-only" for="companion-message">Ваш вопрос спутнику</label><input id="companion-message" name="message" placeholder="Хочу лучше понимать клиента…" maxlength="2000" autocomplete="off" required><button class="companion-send" type="submit" aria-label="Отправить вопрос">${icon('arrow')}</button></form><p id="chat-status" class="companion-chat-status" role="status">Ответ по вашему профилю и каталогу. Голос появится позже.</p></section>`;
}

function personalQuest(data,profile){
  const quest=data.quest||data.personal_quest,options=data.quest_options||(profile?.available_steps||[]).filter(event=>!event.mandatory);
  const status={active:'Квест выбран',completed:'Завершён',unavailable:'Условия изменились',paused:'На паузе'};
  return `<section class="companion-quest" aria-label="Личный квест"><div class="companion-quest-description"><span class="companion-quest-symbol">${icon('target')}</span><div><h2>${quest?e(quest.title):'Один шаг, который выбираете вы'}</h2><p>${quest?`${e(status[quest.status]||'Личный квест')} · ${quest.status==='completed'?'Ваш выбор стал настоящим результатом. Можно выбрать следующий.':'Завершите выбранную активность с приростом навыка, чтобы открыть шапку личного квеста.'}`:'Выберите свой квест. Завершение с приростом навыка открывает особый головной убор.'}</p>${quest?'<button type="button" class="text-button" data-action="quest-clear">Снять квест</button>':''}</div></div>${data.enabled&&options.length?`<form id="quest-form" class="companion-quest-form"><label class="field" for="companion-quest-event">${quest?'Следующий или другой квест':'Ваш личный квест'}</label><div><select id="companion-quest-event" name="event_id" required><option value="">Выберите активность</option>${options.map(event=>`<option value="${e(event.event_id)}" ${quest?.event_id===event.event_id?'selected':''}>${e(event.title)} · ${n(event.duration_hours)} ч</option>`).join('')}</select><button class="button secondary" type="submit">Выбрать</button></div><div class="form-error" role="alert"></div></form>`:`<p class="companion-quest-hint">${!data.enabled?'Включите награды, чтобы выбрать личный квест.':'Для текущей цели пока нет доступных добровольных активностей.'}</p>`}</section>`;
}
function homeView(data,profile){return `<div class="companion-home">${stageView(data)}<div class="companion-coach">${learningPath(data,profile)}${companionChatView()}</div></div>${nextReward(data)}${personalQuest(data,profile)}`;}

function branchStatus(branch){return branch.required==null?'Вне текущей цели':branch.current>=branch.required?'Требование покрыто':`До цели: ${n(branch.required-branch.current)} ур.`;}
function treeView(data,profile,selectedSkill){
  const all=branches(data),selected=all.find(branch=>branch.skill_id===selectedSkill)||all.find(branch=>branch.critical&&branch.current<branch.required)||all[0];
  if(!all.length)return `<section class="companion-empty">${icon('skills')}<h2>Дерево начинается с ваших навыков</h2><p>После загрузки оценки появятся освоенные уровни и доступные шаги развития.</p><a class="button secondary" href="#skills">Мои навыки ${icon('arrow')}</a></section>`;
  return `<div class="companion-tree-layout"><section class="companion-tree" aria-label="Древо навыков"><div class="companion-tree-head"><div><h2>Каждая ветвь — новый навык</h2><p>Уровни растут после завершённых активностей и оценки.</p></div><div class="companion-tree-legend"><span><i class="earned"></i> Освоено</span><span><i class="next"></i> Следующий</span><span><i class="locked"></i> Впереди</span></div></div><div class="companion-branches">${all.map(branch=>`<div class="companion-branch ${selected?.skill_id===branch.skill_id?'selected':''}"><button class="companion-branch-name" data-action="companion-skill" data-id="${e(branch.skill_id)}" aria-pressed="${selected?.skill_id===branch.skill_id}"><span>${e(branch.name)}</span><small>${e(branchStatus(branch))}</small></button><div class="companion-nodes">${(branch.nodes||[]).map(node=>`<button class="companion-node ${e(node.status)} ${node.level===branch.required?'goal-node':''}" data-action="companion-skill" data-id="${e(branch.skill_id)}" data-level="${n(node.level)}" aria-label="${e(branch.name)}, уровень ${n(node.level)}, ${node.status==='earned'?'освоен':node.status==='next'?'следующий шаг':'впереди'}${node.level===branch.required?', требование цели':''}"><span>${node.status==='earned'?icon('check'):n(node.level)}</span>${node.level===branch.required?'<small>цель</small>':''}</button>`).join('')}</div></div>`).join('')}</div><div class="companion-tree-root">${icon('target')}<div><span>Ваша цель</span><strong>${e(goalName(data.tree?.goal||profile?.goal))}</strong></div><button class="text-button" data-action="goal">Изменить</button></div></section>${branchDetails(selected,data)}</div>`;
}

function branchDetails(branch,data){
  if(!branch)return '';
  const activities=branch.activities||[];
  return `<aside class="companion-branch-detail" aria-label="Развитие навыка ${e(branch.name)}"><div class="companion-branch-badge">${icon('skills')}</div><h2>${e(branch.name)}</h2><p class="companion-branch-level"><strong>${n(branch.current)}</strong><span>уровень сейчас${branch.required!=null?`<br>для цели нужен ${n(branch.required)}`:''}</span></p><p>${branch.required==null?'Этот навык не входит в текущую карьерную цель. Его развитие остаётся частью вашего профиля.':branch.current>=branch.required?'Требование цели по этому навыку уже покрыто. Освоенные уровни остаются в вашем профиле.':`Следующие активности помогают сократить разрыв до цели${branch.critical?' по ключевому навыку':''}.`}</p><h3>${activities.length?'Как открыть следующий уровень':'Что дальше'}</h3>${activities.length?activities.map(activity=>`<article class="companion-tree-activity"><div><h4>${e(activity.title)}</h4><span>${e(label(activity.type||activity.format))} · ${n(activity.duration_hours)} ч</span></div><strong>${n(activity.before)} → ${n(activity.after)}</strong><button class="text-button" data-action="event" data-id="${e(activity.event_id)}">Подробнее ${icon('arrow')}</button><button class="text-button" data-action="forecast" data-id="${e(activity.event_id)}">Эффект для цели</button></article>`).join(''):'<p class="companion-no-step">В текущем каталоге нет доступного шага с приростом этого навыка. Спутник может объяснить ограничения.</p>'}${ask('Как развить '+branch.name+'?',{skill:branch.skill_id})}</aside>`;
}

function wardrobeView(data,previewItem){
  const items=wardrobe(data),preview=selectedItem(data,previewItem);
  return `<div class="companion-wardrobe-layout"><div class="companion-fitting-room">${stageView(data,{previewItem,compact:true})}${preview?`<div class="companion-fitting-action"><div><h2>${e(itemName(preview))}</h2><p>${e(preview.description)}</p></div>${preview.unlocked?`<button class="button" data-action="wardrobe-equip" data-id="${e(preview.id)}" ${preview.equipped?'disabled':''}>${preview.equipped?'Уже надето':'Надеть'} ${icon('check')}</button>`:`<span class="companion-lock-reason">${icon('lock')} ${e(preview.requirement?.label||'Откроется за развитие')}</span>`}</div>`:'<p class="companion-fitting-help">Выберите вещь, чтобы примерить. Открытые вещи можно надеть и сохранить.</p>'}</div><section class="companion-wardrobe" aria-label="Гардероб спутника"><div class="companion-section-head"><div><h2>Истории, которые можно надеть</h2><p>${items.filter(item=>item.unlocked).length} из ${items.length} открыто · за ваши шаги в развитии</p></div></div>${Object.entries(slotNames).map(([slot,name])=>{const group=items.filter(item=>item.slot===slot);return group.length?`<section class="companion-wardrobe-group"><h3>${name}</h3><div class="companion-item-grid">${group.map(item=>`<article class="companion-item ${item.unlocked?'unlocked':'locked'} ${item.equipped?'equipped':''} ${preview?.id===item.id?'previewed':''}"><button class="companion-item-preview" data-action="wardrobe-preview" data-id="${e(item.id)}" aria-label="Примерить: ${e(itemName(item))}${item.unlocked?'':', ещё не открыто'}">${wardrobeThumbnail(item)}<span class="companion-item-state">${item.equipped?icon('check'):!item.unlocked?icon('lock'):icon('eye')}</span></button><h4>${e(itemName(item))}</h4><p>${e(item.requirement?.label||item.description)}</p>${item.unlocked?`<button class="companion-equip" data-action="wardrobe-equip" data-id="${e(item.id)}" ${item.equipped?'disabled':''}>${item.equipped?'На спутнике':'Надеть'} ${icon(item.equipped?'check':'plus')}</button>`:`<span class="companion-item-progress">${n(item.requirement?.current)} / ${n(item.requirement?.target)}</span>`}</article>`).join('')}</div></section>`:''}).join('')}${!items.length?'<p class="companion-no-step">Гардероб пока не загружен. Обновите страницу, чтобы получить награды с сервера.</p>':''}</section></div>`;
}

export function companionView(data,profile,{tab='home',selectedSkill=null,previewItem=null}={}){
  if(!data)return `<section class="companion-empty">${icon('sparkles')}<h1>Спутник скоро появится</h1><p>Для вашей мастерской нужны данные профиля. Обновите страницу или вернитесь к своему пути.</p><a class="button" href="#home">Мой путь ${icon('arrow')}</a></section>`;
  const active=['home','tree','wardrobe'].includes(tab)?tab:'home',coverage=data.tree?.coverage_pct;
  return `<div class="companion-page"><header class="companion-heading"><div><h1>Растём вместе</h1><p>Навыки открывают возможности. Ваш спутник делает этот путь заметным.</p></div><div class="companion-goal-progress"><span>${coverage==null?'Выберите цель развития':`До цели · ${n(coverage)}% требований покрыто`}</span>${progress(coverage,'Покрытие карьерной цели')}</div></header><nav class="companion-tabs" aria-label="Разделы спутника">${[['home','Мой спутник','sparkles'],['tree','Древо навыков','skills'],['wardrobe','Гардероб','briefcase']].map(([id,name,symbol])=>`<button type="button" data-action="companion-tab" data-id="${id}" class="${active===id?'active':''}" aria-current="${active===id?'page':'false'}">${icon(symbol)}<span>${name}</span>${id==='wardrobe'?`<small>${wardrobe(data).filter(item=>item.unlocked).length}</small>`:''}</button>`).join('')}</nav>${!data.enabled?'<div class="companion-opt-in"><div><strong>Навыки уже растут. Добавим награды?</strong><p>Новые завершённые активности будут открывать одежду и предметы. Ваши навыки и гардероб сохраняются.</p></div><button class="button" data-action="gamification-toggle" data-enabled="true">Включить награды</button></div>':''}${active==='tree'?treeView(data,profile,selectedSkill):active==='wardrobe'?wardrobeView(data,previewItem):homeView(data,profile)}<footer class="companion-footer"><span>${icon('lock')} Личный прогресс · без рейтинга и штрафов за паузы</span>${data.enabled?'<button class="text-button" data-action="gamification-toggle" data-enabled="false">Приостановить награды</button>':''}</footer></div>`;
}

export function companionCard(data){
  if(!data)return '';
  const next=data.next_unlock;
  return `<section class="companion-entry" aria-label="Ваш спутник"><div class="companion-entry-symbol">${icon('sparkles')}</div><div><h2>Большой рост — из маленьких открытий</h2><p>${next?`${e(itemName(next))}: ${e(strip(next.requirement?.label||next.description))}`:'Ваши навыки, новые образы и спутник, который поможет выбрать следующий шаг.'}</p></div><a class="button secondary" href="#companion">К спутнику ${icon('arrow')}</a></section>`;
}

export function companionCompletion(result,data=null){
  const reward=result?.companion||result?.gamification||data;
  const items=result?.wardrobe_unlocked||result?.unlocked_items||result?.reward?.unlocked_items||reward?.new_unlocks||[];
  const changes=(result?.changes||[]).filter(change=>safeNumber(change.after)>safeNumber(change.before));
  if(!items.length&&!changes.length)return '';
  return `<section class="companion-completion"><div class="companion-completion-symbol">${icon('sparkles')}</div><div><h2>${items.length?'Новый образ. Настоящий прогресс.':'Ваша ветвь стала сильнее'}</h2><p>${items.length?`Открыто: ${items.map(item=>e(typeof item==='string'?item:itemName(item))).join(', ')}.`:changes.map(change=>`${e(change.name||change.skill_id)}: ${n(change.before)} → ${n(change.after)}`).join(' · ')}</p><a class="button secondary" href="#companion">Посмотреть у спутника ${icon('arrow')}</a></div></section>`;
}
