import {escapeHtml as e,number as n,date,pct,label} from './ui.js';

const statusLabel={active:'В процессе',completed:'Завершён',unavailable:'Сейчас недоступен',paused:'На паузе'};
const toggle=data=>`<button class="button ${data.enabled?'secondary':''}" data-action="gamification-toggle" data-enabled="${!data.enabled}">${data.enabled?'Приостановить достижения':'Включить достижения'}</button>`;
const progress=data=>{
  const {current=0,required=null}=data.level_progress||{};
  if(required===null)return '<p class="stat-note">Все уровни открыты. Ваши новые шаги продолжат сохраняться.</p>';
  const value=required>0?pct(current/required*100):0;
  return `<div class="meter" role="meter" aria-label="Прогресс уровня" aria-valuemin="0" aria-valuemax="${e(required)}" aria-valuenow="${e(current)}"><div class="meter-fill" style="width:${value}%"></div></div><p class="stat-note">${n(current)} из ${n(required)} XP до следующего уровня</p>`;
};

export function gamificationCard(data){
  if(!data)return '';
  return `<section class="panel achievement-summary" aria-label="Личные достижения"><div class="achievement-emblem" aria-hidden="true">◇</div><div><p class="eyebrow">ЛИЧНЫЕ ДОСТИЖЕНИЯ</p><h2>${data.enabled?`Уровень ${n(data.level)} · ${e(data.level_name)}`:'Развитие в вашем темпе'}</h2><p class="muted">${data.enabled?`${n(data.xp)} XP · ${data.quest?`Квест: ${e(data.quest.title)} · ${e(statusLabel[data.quest.status]||data.quest.status)}`:'Выберите личный квест из доступных шагов.'}`:'При желании включите опыт, уровни и значки за завершённые активности.'}</p>${data.enabled?progress(data):'<p class="stat-note">Добровольно, без рейтингов и штрафов.</p>'}</div><a class="button secondary" href="#achievements">${data.enabled?'Мои достижения →':'Посмотреть →'}</a></section>`;
}

function questView(data,profile){
  const quest=data.quest;
  const candidates=(profile.available_steps||[]).filter(event=>!event.mandatory);
  const gains=quest?.expected_gains||[];
  return `<section class="panel quest-panel"><div class="section-heading"><div><p class="eyebrow">ОДИН ПОНЯТНЫЙ ШАГ</p><h2>Личный квест</h2></div>${quest?`<span class="pill ${quest.status==='active'||quest.status==='completed'?'':'neutral'}">${e(statusLabel[quest.status]||quest.status)}</span>`:''}</div>${quest?`<h3>${e(quest.title)}</h3>${gains.length?`<p class="gain">${gains.map(g=>`${e(g.name||profile.skill_names?.[g.skill_id]||g.skill_id)}: <strong>${n(g.before)} → ${n(g.after)}</strong>`).join('<br>')}</p>`:''}${quest.unavailable_reasons?.length?`<p class="explanation">${quest.unavailable_reasons.map(reason=>e(label(reason.code||reason))).join(' · ')}</p>`:''}<p class="muted">${quest.status==='completed'?'Квест завершён. Можно выбрать следующий шаг, когда будете готовы.':quest.status==='unavailable'?'Условия изменились. Выберите другой доступный шаг.':quest.status==='paused'?'Квест сохранён. Продолжите, когда захотите включить достижения.':'Выбор квеста сохраняет ваш фокус. Начните активность в каталоге, а после прохождения отметьте выполнение в истории.'}</p><div class="form-actions">${data.enabled&&quest.status==='active'?'<a class="button secondary" href="#catalog">Перейти к активности →</a>':''}<button class="text-button" data-action="quest-clear">Снять квест</button></div>`:'<p class="muted">Выберите активность, на которой хотите сосредоточиться. Без дедлайна и штрафа за смену.</p>'}${data.enabled?(candidates.length?`<form id="quest-form"><label class="field">${quest?'Выбрать следующий или заменить квест':'Доступный шаг'}<select name="event_id" required><option value="">Выберите активность</option>${candidates.map(event=>`<option value="${e(event.event_id)}" ${quest?.event_id===event.event_id?'selected':''}>${e(event.title)} · ${n(event.duration_hours)} ч</option>`).join('')}</select></label><div class="form-error"></div><button class="button" type="submit">Выбрать квест</button></form>`:'<div class="info">Для текущей цели нет доступных шагов. Вернитесь к траектории или измените цель.</div>'):'<p class="explanation">Для выбора квеста включите достижения. Навыки и история доступны независимо от этого.</p>'}</section>`;
}

export function gamificationView(data,profile){
  if(!data)return '<div class="empty"><h1>Достижения недоступны</h1><p>Этот режим предпросмотра показывает основной сценарий. Достижения работают с подключённым сервером.</p><a href="#home">Вернуться к траектории</a></div>';
  return `<div class="page-heading"><div><p class="eyebrow">ВАШ ЛИЧНЫЙ ПРОГРЕСС</p><h1>Достижения</h1><p class="heading-sub">Небольшие шаги, которые складываются в опыт.</p></div>${toggle(data)}</div><div class="info"><strong>${data.enabled?'Достижения включены':'Достижения выключены'}</strong><p>${e(data.privacy)}</p>${!data.enabled?'<p>Участие добровольное. Сохранённые награды остаются у вас; за активности во время паузы XP не начисляется.</p>':''}</div><div class="stats"><article class="stat"><div class="stat-label">${e(data.level_name)}</div><div class="stat-value">${n(data.level)} <small>уровень</small></div>${progress(data)}</article><article class="stat"><div class="stat-label">Опыт развития</div><div class="stat-value">${n(data.xp)} <small>XP</small></div><div class="stat-note">Личный показатель, не оценка работы</div></article><article class="stat"><div class="stat-label">Шаги с наградой</div><div class="stat-value">${n(data.completed_count)} <small>активностей</small></div><div class="stat-note">Прирост навыков: ${n(data.skill_levels_gained)} ур.</div></article></div><div class="grid-two">${questView(data,profile)}<section class="panel"><h2>Как начисляется опыт</h2><ul class="achievement-rules">${(data.rules||[]).map(rule=>`<li>${e(rule)}</li>`).join('')}</ul><p class="explanation">Можно отключить достижения в любой момент. Ваши навыки, история и рекомендации продолжат работать.</p></section></div><section class="achievement-section"><div class="section-heading"><div><h2>Значки</h2><p>Каждый отмечает конкретный результат</p></div></div><div class="badge-grid">${(data.badges||[]).map(badge=>`<article class="achievement-badge ${badge.earned?'earned':''}"><span class="badge-symbol" aria-hidden="true">${badge.earned?'✦':'◇'}</span><div><span class="pill ${badge.earned?'':'neutral'}">${badge.earned?'Получен':'Ещё впереди'}</span><h3>${e(badge.title)}</h3><p>${e(badge.description)}</p>${badge.earned_at?`<small>${e(date(badge.earned_at))}</small>`:''}</div></article>`).join('')}</div></section><section class="panel achievement-section"><h2>Последние награды</h2>${data.recent_rewards?.length?data.recent_rewards.map(reward=>`<div class="history-item"><span class="history-icon" aria-hidden="true">✓</span><div><p class="history-title">${e(reward.title)}</p><div class="history-meta">${e(date(reward.earned_at))} · +${n(reward.xp)} XP · прирост навыков ${n(reward.gained_levels)} ур.</div></div></div>`).join(''):'<p class="muted">Здесь появятся награды за новые завершения после включения достижений.</p>'}</section>`;
}

export function rewardFeedback(reward){
  return reward?.awarded?`<p class="reward-feedback">+${n(reward.xp)} XP к личным достижениям · прирост навыков ${n(reward.gained_levels)} ур.</p>`:'';
}
