export const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
export const pct=value=>Number.isFinite(Number(value))&&value!==null?Math.min(100,Math.max(0,Number(value))):null;
export const number=value=>Number.isFinite(Number(value))&&value!==null?new Intl.NumberFormat('ru-RU',{maximumFractionDigits:1}).format(Number(value)):'—';
export function date(value){if(!value)return 'Дата не указана';const parsed=new Date(/^\d{4}-\d{2}-\d{2}$/.test(value)?value+'T12:00:00':value);return Number.isNaN(parsed.getTime())?'Дата не указана':parsed.toLocaleDateString('ru-RU',{day:'numeric',month:'short',year:'numeric'});}
export const labels={completed:'Завершено',in_progress:'В процессе',dropped:'Прервано',no_show:'Пропуск',declined:'Отказ',overdue:'Просрочено',online:'Онлайн',offline:'Очно',self_paced:'В своём темпе',employee:'Сотрудник',hr:'HR',no_goal:'Выберите цель развития',goal_achieved:'Требования цели уже покрыты',no_candidates:'Пока нет подходящего шага',audience:'Ограничения роли или грейда',prerequisites:'Нужна предварительная подготовка',no_gain:'Нет полезного прироста',no_sessions:'Нет доступных дат',goal_outside_catalog:'Цель вне покрытия каталога',not_configured:'AI не настроен',timeout:'AI не ответил вовремя',unavailable:'AI временно недоступен'};
Object.assign(labels,{role_not_eligible:'Не подходит текущая роль',grade_not_eligible:'Не подходит текущий грейд',prerequisites_not_met:'Нужна предварительная подготовка',already_completed:'Уже пройдено',no_available_session:'Нет доступной сессии',goal_not_set:'Цель не выбрана',no_target_gain:'Нет прироста для цели',mandatory:'Обязательное мероприятие'});
export const label=value=>labels[value]||value||'—';
Object.assign(labels,{course:'Курс',workshop:'Практикум',mentoring:'Менторство',certification:'Сертификация',meetup:'Встреча',compliance:'Обязательная программа',onboarding:'Адаптация',incomplete_data:'Недостаточно данных для расчёта',not_available:'Активность пока недоступна',stale_forecast:'Профиль изменился. Обновите прогноз',assessment_unavailable:'Нет исходной оценки для восстановления истории',event_history_unavailable:'В каталоге нет данных об этой активности',included_in_assessment_or_not_completed:'Результат уже включён в исходную оценку или активность ещё не завершена'});
export function validRecommendation(item){return typeof item.event_id==='string'&&Array.isArray(item.factors)&&item.factors.filter(f=>typeof(f.text??f)==='string'&&String(f.text??f).trim()).length>=3;}
export function sourceLabel(result){if(result.source==='ai')return result.cached?'AI · сохранённый ответ':'AI-рекомендации';if(result.source==='preview')return 'Пример интерфейса';if(result.source==='none')return 'Состояние траектории';return 'Резервный подбор · без AI';}
