import {escapeHtml as e,number as n,date,pct,label,validRecommendation,sourceLabel} from './ui.js';
import {icon} from './icons.js';
import {gamificationCard,rewardFeedback} from './gamification.js';
import {forecast,eventById,filterEvents,skillTimeline,historyResult} from './domain.js';
import {hrProfileView,importView} from './views-hr.js';
export {hrView,employeesView,hrProfileView,importView,importResult,settingsView,createAccessForm} from './views-hr.js';

export const button=(text,action,extra='')=>`<button class="button" data-action="${e(action)}" ${extra}>${text}</button>`;
export const empty=(title,text,action='')=>`<div class="empty"><span class="empty-icon">${icon('info')}</span><h3>${e(title)}</h3><p>${e(text)}</p>${action}</div>`;
export const heading=(_eyebrow,title,text,action='')=>`<div class="page-heading"><div><h1>${e(title)}</h1>${text?`<p class="heading-sub">${e(text)}</p>`:''}</div>${action}</div>`;
export const loadingView=(text='Загружаем данные…')=>`<div class="loading" role="status">${e(text)}</div>`;
export const errorView=error=>`<div class="error" role="alert">${icon('alert-circle')}<div><strong>${e(error.message||'Не удалось выполнить действие.')}</strong>${Array.isArray(error.details)&&error.details.length?`<ul>${error.details.map(detail=>`<li>${e(detail.file||'')} ${e(detail.row??detail.object??'')} ${e(detail.field||detail.loc?.join('.')||'')}: ${e(detail.message||detail.msg||'')}</li>`).join('')}</ul>`:''}</div></div>`;
const meter=(value,title='Покрытие требований цели')=>`<div class="meter" role="meter" aria-label="${e(title)}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${pct(value)??0}"><div class="meter-fill" style="width:${pct(value)??0}%"></div></div>`;
const closeButton=()=>`<button class="icon-button" data-action="close-dialog" type="button" aria-label="Закрыть">${icon('close')}</button>`;
const dialogHead=(title,id='detail-title',subtitle='')=>`<div class="dialog-head"><div><h2 id="${id}">${e(title)}</h2>${subtitle?`<p class="muted">${e(subtitle)}</p>`:''}</div>${closeButton()}</div>`;
const goalText=goal=>goal?.target_role?`${goal.target_role} · ${goal.target_grade}`:'Цель пока не выбрана';
const known=value=>value!==null&&value!==undefined&&Number.isFinite(Number(value));
const reasonText=code=>({incomplete_data:'Для точного расчёта недостаточно данных.',not_available:'Активность пока недоступна для вашей траектории.',stale_forecast:'Данные изменились. Обновите профиль и повторите расчёт.',assessment_unavailable:'Базовая оценка навыков не сохранена.',event_history_unavailable:'Недостаточно данных о прошлой активности.',included_in_assessment_or_not_completed:'Результат уже включён в базовую оценку либо активность ещё не завершена.'}[code]||label(code));
const delta=value=>`${Number(value)>0?'+':''}${n(value)}`;
function levelDots(current,required){
  const value=known(current)?Math.max(0,Math.min(5,Number(current))):0;
  return `<span class="level-dots" role="img" aria-label="Текущий уровень ${e(n(current))} из 5${known(required)?', для цели '+e(n(required)):''}">${[1,2,3,4,5].map(i=>`<span class="level-dot ${i<=value?'filled':''} ${i===Number(required)?'target':''}"></span>`).join('')}</span>`;
}
function metadata(event){
  const session=event.session_date||event.next_session;
  return `<div class="chips"><span class="pill neutral">${icon('book-open')} ${e(label(event.type||event.format))}</span><span class="pill neutral">${icon('clock')} ${n(event.duration_hours)} ч</span><span class="pill neutral">${icon('calendar')} ${event.format==='self_paced'?'В удобное время':e(date(session))}</span></div>`;
}
function actionFor(event,{secondary=false}={}){
  if(!event||event.mandatory)return '';
  if(event.action==='continue'&&event.record_id)return `<button class="button ${secondary?'secondary':''}" data-action="complete" data-id="${e(event.record_id)}" ${event.can_complete===false?'disabled':''}>${event.can_complete===false?'Сессия ещё не состоялась':'Отметить выполнение'} ${icon('check')}</button>`;
  if(!event.eligible)return '<button class="button secondary" disabled>Пока недоступно</button>';
  return `<button class="button ${secondary?'secondary':''}" data-action="start" data-id="${e(event.event_id)}" data-session="${e(event.session_date||event.next_session||'')}">Начать ${icon('arrow-right')}</button>`;
}
function effectList(changes=[]){
  return changes.length?`<div class="gains">${changes.map(change=>`<div class="gain-row"><span>${e(change.name||change.skill_id)}</span><strong>${n(change.before)} <span class="muted">→</span> ${n(change.after)}</strong></div>`).join('')}</div>`:'<p class="muted">Изменение уровней не указано.</p>';
}
function forecastMetrics(result){
  const snapshot=result.goal_snapshot||result.target_before||result.target_after;
  return `${snapshot?`<p class="explanation">Цель на момент выполнения: ${e(goalText(snapshot))}.</p>`:''}<div class="forecast-value"><span class="muted">Покрытие требований цели</span><div>${known(result.coverage_before)&&known(result.coverage_after)?`<strong>${n(result.coverage_before)}% <span>→</span> ${n(result.coverage_after)}%</strong><span class="pill ${result.coverage_after>result.coverage_before?'success':'neutral'}">${delta(result.coverage_after-result.coverage_before)} п. п.</span>`:'<strong>Не рассчитано</strong>'}</div></div>${effectList(result.changes)}${known(result.critical_before)&&known(result.critical_after)?`<div class="gain-row"><span>Критические разрывы</span><strong>${n(result.critical_before)} → ${n(result.critical_after)}</strong></div>`:''}`;
}
function unlocksView(unlocks=[],predicted=false){
  return unlocks.length?`<section class="unlock-section"><h3>${predicted?'Могут стать доступны':'Новые доступные возможности'}</h3><ul class="simple-list">${unlocks.map(event=>`<li>${icon('lock')} <span>${e(event.title||event.event_id)}</span></li>`).join('')}</ul>${predicted?'<p class="muted">Прогноз по текущим условиям каталога. Доступность после завершения проверит сервер.</p>':''}</section>`:'';
}

export function loginView(remembered=''){
  return `<div class="login-layout"><section class="login-form-side"><a class="brand" href="#home"><span class="brand-wordmark">Halyk<span class="brand-dot"></span></span><span class="brand-product">Career Quest</span></a><div class="login-content"><h1>Добро пожаловать<br>в Career Quest</h1><p class="heading-sub">Развивайтесь. Растите. Вместе с Halyk.</p><form id="login-form"><label class="field">Логин<input name="username" value="${e(remembered)}" autocomplete="username" required maxlength="120" placeholder="Введите логин"></label><label class="field">Пароль<input name="password" type="password" autocomplete="current-password" required placeholder="Введите пароль"></label><div class="auth-tools"><label class="check-row"><input type="checkbox" name="remember" ${remembered?'checked':''}>Запомнить логин</label><button type="button" class="button text small" data-action="forgot-password">Забыли пароль?</button></div><div class="form-error"></div><button type="submit" class="button login-submit">Войти ${icon('arrow-right')}</button></form><p class="auth-note">Личное пространство для вашего развития. Доступ к профилю выдаёт HR.</p></div><p class="login-footer muted">Halyk Career Quest · Развитие начинается здесь</p></section><aside class="login-photo"><img src="/static/assets/login-team.jpg" alt="Команда на рабочей встрече"><div class="login-copy"><h2>Люди создают большее</h2><p>Карьерное развитие начинается здесь.</p></div></aside></div>`;
}

export function setupView(status={}){
  const aiReady=['ready','connected'].includes(status.ai_status);
  const step=status.setup_required?1:!status.dataset_loaded?2:!aiReady?3:4;
  const content=status.setup_required?`<section class="panel"><h2>Создайте аккаунт HR</h2><p class="muted">Он нужен для импорта данных и настройки приложения.</p><form id="bootstrap-form"><label class="field">Логин HR<input name="username" autocomplete="username" required minlength="3" maxlength="120"></label><label class="field">Пароль<input name="password" type="password" autocomplete="new-password" required minlength="10"><small>Не менее 10 символов.</small></label><div class="form-error"></div><button type="submit" class="button">Создать аккаунт ${icon('arrow-right')}</button></form></section>`:!status.dataset_loaded?importView(true):step===3?`<section class="panel"><h2>Подключите AI</h2><p>Данные загружены. Настройте OpenAI или NVIDIA, чтобы получать объяснения следующего шага.</p><a class="button" href="#settings">Настроить AI ${icon('arrow-right')}</a><div class="form-actions"><a class="button text" href="#home">Перейти в рабочее пространство</a></div></section>`:`<section class="panel"><span class="completion-icon">${icon('check-circle')}</span><h2>Пространство готово</h2><p>Данные загружены. AI-модуль подключён. Доступность модели и ключа можно проверить в настройках.</p><div class="form-actions"><a class="button" href="#home">Открыть обзор команды ${icon('arrow-right')}</a><a class="button secondary" href="#settings">Настройки AI</a></div></section>`;
  return `<div class="setup-layout">${heading('','Первый запуск','Подготовим пространство карьерного развития.')}<div class="steps setup-steps" aria-label="Этапы настройки">${['HR аккаунт','Данные',aiReady?'AI-модуль подключён':'AI','Готово'].map((text,i)=>`<span class="step ${i+1<step?'done':i+1===step?'active':''}" ${i+1===step?'aria-current="step"':''}><span>${i+1<step?icon('check'):i+1}</span>${text}</span>`).join('')}</div><div class="setup-grid"><div>${content}</div><aside class="setup-context"><span class="setup-context-icon">${icon(step===1?'lock':step===2?'upload':step===3?'sparkles':'check-circle')}</span><h2>Одно пространство для развития</h2><p>Сотрудник видит свой путь, навыки и доступные активности. HR помогает команде выбирать следующий шаг.</p><p class="muted">Данные и прогресс сохраняются на этом компьютере.</p></aside></div></div>`;
}

function skillRow(skill,{covered=false}={}){
  const missing=Math.max(0,Number(skill.required)-Number(skill.current));
  return `<article class="skill-row"><div class="skill-row-main"><span class="skill-status-icon ${covered?'success':skill.critical?'danger':'warn'}">${icon(covered?'check-circle':'alert-circle')}</span><div><h3>${e(skill.name||skill.skill_id)}</h3><p class="muted">${covered?'Требование покрыто':`Не хватает ${n(missing)} ${missing===1?'уровня':'уровней'}`}</p></div></div><div class="skill-level"><strong>${n(skill.current)} <span class="muted">/ ${n(skill.required)}</span></strong>${levelDots(skill.current,skill.required)}</div>${skill.critical&&!covered?'<span class="pill danger">Критический</span>':''}<button class="button text small" data-action="skill" data-id="${e(skill.skill_id)}">${covered?'Подробнее':'Развить'} ${icon('arrow-right')}</button></article>`;
}
export function skillsView(skills=[]){
  return skills.length?`<div class="skill-list">${skills.map(skill=>skillRow(skill,{covered:Number(skill.current)>=Number(skill.required)})).join('')}</div>`:empty('Требования не заданы','Выберите карьерную цель, чтобы увидеть нужные навыки.');
}
function skillsPage(profile){
  const skills=profile.skills||[],gaps=skills.filter(s=>Number(s.current)<Number(s.required)),covered=skills.filter(s=>Number(s.current)>=Number(s.required));
  return `${heading('','Навыки',goalText(profile.goal),button(`Изменить цель ${icon('target')}`,'goal'))}<section class="panel progress-summary"><div><h2>Готовность к требованиям</h2><p class="muted">${n(gaps.length)} навыков требуют внимания</p></div><strong>${known(profile.coverage_pct)?n(profile.coverage_pct)+'%':'—'}</strong>${known(profile.coverage_pct)?meter(profile.coverage_pct):''}</section>${gaps.length?`<section class="panel"><div class="section-heading"><h2>Требуют развития</h2><span class="pill warn">${n(gaps.length)}</span></div>${skillsView(gaps.sort((a,b)=>Number(Boolean(b.critical))-Number(Boolean(a.critical))))}</section>`:''}${covered.length?`<section class="panel"><div class="section-heading"><h2>Требования покрыты</h2><span class="pill success">${n(covered.length)}</span></div>${skillsView(covered)}</section>`:''}${skills.length?'':empty('Начните с карьерной цели','Выберите роль и грейд, чтобы увидеть требования.',button('Выбрать цель','goal'))}`;
}

function historyRecord(record,readOnly=false){
  return `<article class="history-item"><span class="history-icon ${record.status==='completed'?'success':''}">${icon(record.status==='completed'?'check-circle':'clock')}</span><div class="history-content"><div class="history-row-head"><h3>${e(record.title||record.event_id)}</h3><span class="pill ${record.status==='completed'?'success':record.status==='in_progress'?'neutral':'warn'}">${e(label(record.status))}</span></div><p class="muted">${e(date(record.date))}${record.completion_pct!==undefined?' · выполнено '+n(record.completion_pct)+'%':''}</p>${record.status==='in_progress'&&known(record.completion_pct)?meter(record.completion_pct,'Выполнение активности'):''}${readOnly?'':`<div class="record-actions">${record.can_complete?`<button class="button secondary small" data-action="complete" data-id="${e(record.record_id)}">Отметить выполнение ${icon('check')}</button>`:record.status==='in_progress'?`<span class="muted">${record.mandatory?'Обязательная активность: статус обновляется через импорт':'Завершение станет доступно после сессии.'}</span>`:''}${record.status==='completed'?`<button class="button text small" data-action="history-result" data-id="${e(record.record_id)}">Результат ${icon('arrow-right')}</button>`:''}</div>`}</div></article>`;
}
export function historyView(records=[],readOnly=false){return records.length?`<div class="history-list">${records.map(record=>historyRecord(record,readOnly)).join('')}</div>`:empty('История пока пуста','Начните подходящую активность, и она появится здесь.');}
function historyPage(profile,tab='all'){
  const rows=(profile.history||[]).filter(row=>tab==='all'||row.status===tab);
  return `${heading('','История развития','Ваши начатые и завершённые активности.')}<div class="tabs" aria-label="Фильтр истории">${[['all','Все'],['in_progress','В процессе'],['completed','Завершено']].map(([id,text])=>`<button class="tab ${tab===id?'active':''}" aria-pressed="${tab===id}" data-action="history-tab" data-id="${id}">${text}</button>`).join('')}</div><section class="panel">${rows.length?historyView(rows):empty('В этой группе нет активностей',tab==='all'?'Начните подходящий шаг для развития.':'Посмотрите другие записи в истории.','<a class="button secondary" href="#catalog">К активностям</a>')}</section>`;
}

function recommendationEvent(profile,item){return profile?eventById(profile,item.event_id):null;}
function mainRecommendation(item,profile,readOnly){
  const event=recommendationEvent(profile,item),prediction=profile?forecast(profile,item.event_id):null;
  const gains=prediction?.available?prediction.changes:item.gains||[];
  return `<article class="featured-recommendation"><div class="recommendation-main"><div class="recommendation-top"><span class="pill success">${icon('sparkles')} Рекомендуем</span>${item.action==='continue'?'<span class="pill neutral">В процессе</span>':''}</div><h2>${e(item.title||item.event_id)}</h2>${metadata(item)}<section class="detail-section"><h3>Почему вам подходит</h3><ul class="factors">${item.factors.map(factor=>`<li>${icon('check-circle')}<span>${e(factor.text??factor)}</span></li>`).join('')}</ul></section><div class="card-actions">${profile?`<button class="button secondary" data-action="forecast" data-id="${e(item.event_id)}">${icon('eye')} Что изменится</button>`:''}</div></div><section class="recommendation-effect"><h3>Ожидаемый результат</h3>${effectList(gains)}${prediction?.available&&known(prediction.coverage_before)&&known(prediction.coverage_after)?`<div class="gain-row"><span>Покрытие цели</span><strong>${n(prediction.coverage_before)}% → ${n(prediction.coverage_after)}%</strong></div>`:''}<div class="card-actions">${readOnly?'<span class="muted">Просмотр HR</span>':actionFor(event)}</div></section></article>`;
}
function alternativeCard(item,profile,readOnly,index){
  const event=recommendationEvent(profile,item),prediction=profile?forecast(profile,item.event_id):null;
  return `<article class="activity-card"><span class="pill neutral">Вариант ${index+2}</span><h3>${e(item.title||item.event_id)}</h3>${metadata(item)}${prediction?.available&&known(prediction.coverage_before)&&known(prediction.coverage_after)?`<p class="alternative-impact">${delta(prediction.coverage_after-prediction.coverage_before)} п. п. к покрытию цели</p>`:effectList(item.gains||[])}${item.alternative?`<p class="muted">${e(item.alternative)}</p>`:''}<details class="recommendation-reasons"><summary>Почему подходит</summary><ul class="factors">${item.factors.map(factor=>`<li>${icon('check-circle')}<span>${e(factor.text??factor)}</span></li>`).join('')}</ul></details><div class="form-actions">${profile?`<button class="button text small" data-action="event" data-id="${e(item.event_id)}">Подробнее ${icon('arrow-right')}</button>`:''}${readOnly?'':event?.action==='continue'?actionFor(event,{secondary:true}):''}</div></article>`;
}
export function recommendationView(result,readOnly=false,profile=null){
  if(!result)return empty('Найдём ваш следующий шаг','Рекомендации учитывают карьерную цель, навыки и историю участия.',readOnly?'':button(`Подобрать рекомендации ${icon('sparkles')}`,'recommend'));
  const states={no_goal:['Выберите направление развития','Укажите роль и грейд, к которым хотите двигаться.'],goal_achieved:['Требования цели покрыты','Можно выбрать следующую цель развития. Покрытие навыков не означает автоматическое повышение.'],no_candidates:['Пока нет подходящей активности','В текущем каталоге нет доступного шага для вашей цели. HR может помочь с дальнейшим развитием.']};
  if(states[result.status])return empty(...states[result.status],readOnly?'':result.status==='no_goal'||result.status==='goal_achieved'?button('Выбрать цель','goal'):'<a class="button secondary" href="#catalog">Открыть каталог</a>')+(result.reasons?.length?`<p class="explanation">${result.reasons.map(reason=>e(reasonText(reason.code||reason))).join(' · ')}</p>`:'');
  const items=(result.items||[]).filter(validRecommendation).slice(0,3);
  if(!items.length)return empty('Рекомендации пока недоступны',result.message||'Не удалось получить проверенные рекомендации с тремя факторами.',readOnly?'':button('Повторить подбор','recommend'));
  return `${result.source==='ai'?'':`<div class="info">${icon('info')}<span>${result.source==='preview'?'Это демонстрационные карточки. Реальный AI не вызывался.':`${e(label(result.reason||'unavailable'))}. Показан резервный подбор по правилам, без ответа AI.`}</span></div>`}${mainRecommendation(items[0],profile,readOnly)}${items.length>1?`<div class="section-heading"><h2>Другие варианты</h2>${profile?'<button class="button text" data-action="compare">Сравнить варианты '+icon('arrow-right')+'</button>':''}</div><div class="alternative-grid">${items.slice(1).map((item,index)=>alternativeCard(item,profile,readOnly,index)).join('')}</div>`:''}`;
}

export function employeeView(profile,{readOnly=false,section='home',completion=null,historyTab='all',gamification=null}={}){
  if(readOnly)return hrProfileView(profile);
  if(section==='skills')return skillsPage(profile);
  if(section==='history')return historyPage(profile,historyTab);
  const person=profile.employee||{},skills=profile.skills||[],covered=skills.filter(s=>Number(s.current)>=Number(s.required)).length,gaps=skills.length-covered;
  return `${heading('','Мой путь','Вот ваш прогресс на пути к следующей роли.')}<p class="greeting">Добрый день${person.full_name?', '+e(person.full_name):''}.</p><section class="goal-card panel"><div class="section-heading"><h2>Карьерная цель</h2><button class="button text small" data-action="goal">Изменить ${icon('chevron-right')}</button></div><div class="goal-route"><div><span class="muted">Сейчас</span><strong>${e(person.role||'Роль не указана')} · ${e(person.grade||'—')}</strong></div><span class="goal-arrow">${icon('arrow-right')}</span><div><span class="muted">Ваша цель</span><strong>${e(goalText(profile.goal))}</strong></div></div>${profile.goal?.source==='suggested'?'<p class="muted">Предложен следующий грейд вашей роли. Вы можете выбрать другую цель.</p>':''}<div class="goal-progress"><div class="section-heading"><h3>Готовность к требованиям</h3><strong>${known(profile.coverage_pct)?n(profile.coverage_pct)+'%':'—'}</strong></div>${known(profile.coverage_pct)?meter(profile.coverage_pct):''}<div class="progress-facts"><span>${icon('check-circle')} ${n(covered)} требований покрыто</span><span>${icon('alert-circle')} ${n(gaps)} требуют развития</span></div><p class="explanation">Показатель навыков для цели, а не вероятность повышения.</p></div></section>${completion?`<div class="info completion-inline">${icon('check-circle')}<span>${completion.applied===false?'Это выполнение уже учтено.':'Последняя активность завершена.'}${known(completion.coverage_before)&&known(completion.coverage_after)?` Покрытие: ${n(completion.coverage_before)}% → ${n(completion.coverage_after)}%.`:''}</span></div>`:''}<section><div class="section-heading"><div><h2>Ваш следующий шаг</h2><p class="muted">Подходит вашим навыкам, цели и опыту.</p></div><div class="section-actions">${profile.recommendations?`<span class="pill neutral">${e(sourceLabel(profile.recommendations))}</span>`:''}<button class="button text small" data-action="recommend">Обновить ${icon('sparkles')}</button></div></div><div id="recommendation-content">${recommendationView(profile.recommendations,false,profile)}</div></section>${gamificationCard(gamification)}<div class="grid-two"><section class="panel"><div class="section-heading"><h2>Навыки на пути к цели</h2><a class="button text small" href="#skills">Все навыки ${icon('arrow-right')}</a></div>${skillsView([...skills].sort((a,b)=>Number(Boolean(b.critical))-Number(Boolean(a.critical))).slice(0,4))}</section><section class="panel"><div class="section-heading"><h2>Последние активности</h2><a class="button text small" href="#history">История ${icon('arrow-right')}</a></div>${historyView((profile.history||[]).slice(0,3))}</section></div>`;
}

export function goalForm(profile){
  const options=profile.goal_options||[],person=profile.employee||{};
  return `${dialogHead('Куда хотите двигаться?','goal-dialog-title','Сейчас: '+[person.role,person.grade].filter(Boolean).join(' · '))}<form id="goal-form"><div class="dialog-body"><fieldset class="goal-options"><legend class="muted">Выберите карьерную цель</legend>${options.map((goal,index)=>{const selected=goal.target_role===profile.goal?.target_role&&goal.target_grade===profile.goal?.target_grade;return `<label class="goal-option"><input type="radio" name="goal_index" value="${index}" ${selected?'checked':''} required><span><strong>${e(goal.target_role)}</strong><small>${e(goal.target_grade)}</small></span>${selected?'<span class="pill success">Текущая цель</span>':goal.target_role===person.role?'<span class="pill neutral">В вашей роли</span>':''}</label>`;}).join('')}</fieldset>${options.length?'':empty('Список целей недоступен','Обновите профиль или обратитесь к HR.')}<div class="form-error"></div></div><div class="dialog-footer"><button class="button secondary" type="button" data-action="close-dialog">Отмена</button><button class="button" type="submit" ${options.length?'':'disabled'}>Сохранить цель</button></div></form>`;
}

function activityCard(profile,event){
  const prediction=forecast(profile,event.event_id);
  return `<article class="activity-card panel"><div class="card-top"><span class="event-icon">${icon('book-open')}</span><span class="pill ${event.action==='continue'?'success':event.eligible?'neutral':'warn'}">${event.action==='continue'?'В процессе':event.eligible?'Подходит вам':'Есть ограничения'}</span></div><h3>${e(event.title||event.event_id)}</h3>${metadata(event)}<div class="activity-effects">${effectList(prediction.available?prediction.changes:event.gains||[])}</div>${prediction.available&&known(prediction.coverage_before)&&known(prediction.coverage_after)?`<p class="alternative-impact">${delta(prediction.coverage_after-prediction.coverage_before)} п. п. к покрытию цели</p>`:''}<div class="card-bottom"><button class="button secondary" data-action="event" data-id="${e(event.event_id)}">Подробнее ${icon('arrow-right')}</button></div></article>`;
}
export function availableView(profile,filters={}){
  const active={tab:'suitable',search:'',format:'',duration:'',skills:[],...filters},events=filterEvents(profile,active);
  const filterCount=Number(Boolean(active.format))+Number(Boolean(active.duration))+(active.skills||[]).length;
  return `${heading('','Активности','Найдите следующий шаг для развития.')}<div class="catalog-toolbar"><form id="activity-search" class="search-form"><label class="field"><span class="sr-only">Название, описание или навык</span><input type="search" name="search" value="${e(active.search)}" placeholder="Название, описание или навык"></label><button class="button secondary" type="submit">${icon('search')} Найти</button></form><button class="button secondary" data-action="filters">${icon('filter')} Фильтры${filterCount?` <span class="pill success">${n(filterCount)}</span>`:''}</button></div><div class="section-heading"><div class="tabs" aria-label="Группа активностей">${[['all','Все'],['suitable','Подходят мне'],['ongoing','В процессе']].map(([id,text])=>`<button class="tab ${active.tab===id?'active':''}" aria-pressed="${active.tab===id}" data-action="catalog-tab" data-id="${id}">${text}</button>`).join('')}</div><span class="muted">${n(events.length)} активностей</span></div>${events.length?`<div class="activity-grid">${events.map(event=>activityCard(profile,event)).join('')}</div>`:empty('Активности не найдены',active.search||filterCount?'Попробуйте другие фильтры или поисковый запрос.':active.tab==='ongoing'?'Здесь появятся начатые активности.':'Для текущей цели нет подходящих активностей.',active.search||filterCount?'<button class="button secondary" data-action="reset-catalog">Сбросить фильтры</button>':'<button class="button secondary" data-action="goal">Проверить цель</button>')}<p class="explanation">Доступность определяется условиями участия и вашей целью. Каталог не является AI-рейтингом.</p>`;
}
export function filtersView(profile,filters={}){
  const selected={format:'',duration:'',skills:[],...filters},allSkills=profile.all_skills||[];
  return `${dialogHead('Фильтры')}<form id="activity-filters"><div class="dialog-body"><label class="field">Формат<select name="format"><option value="">Любой формат</option>${['online','offline','self_paced'].map(format=>`<option value="${format}" ${selected.format===format?'selected':''}>${e(label(format))}</option>`).join('')}</select></label><label class="field">Продолжительность<select name="duration"><option value="">Любая</option>${[1,2,4].map(hours=>`<option value="${hours}" ${String(selected.duration)===String(hours)?'selected':''}>До ${hours} ${hours===1?'часа':'часов'}</option>`).join('')}</select></label><fieldset class="skill-filters"><legend>Какие навыки развивать</legend>${allSkills.length?allSkills.map(skill=>`<label class="check-row"><input type="checkbox" name="skills" value="${e(skill.skill_id)}" ${(selected.skills||[]).includes(skill.skill_id)?'checked':''}>${e(skill.name||skill.skill_id)}</label>`).join(''):'<p class="muted">Список навыков пока недоступен.</p>'}</fieldset></div><div class="dialog-footer"><button type="button" class="button secondary" data-action="reset-catalog">Сбросить</button><button type="submit" class="button">Показать <span id="filter-count">${n(filterEvents(profile,selected).length)}</span></button></div></form>`;
}

export function forecastView(profile,id){
  const event=eventById(profile,id),result=forecast(profile,id);
  if(!event)return `${dialogHead('Активность не найдена')}<div class="dialog-body"><p>Обновите каталог и выберите активность снова.</p></div>`;
  return `${dialogHead('Что изменится','detail-title',event.title||event.event_id)}<div class="dialog-body"><span class="pill neutral">${icon('eye')} Прогноз</span>${result.available?`${forecastMetrics(result)}${unlocksView(result.unlocks,true)}<p class="explanation">Расчёт по текущей цели и данным каталога. Прогресс сохраняется только после завершения активности.</p>`:empty('Прогноз пока недоступен',(result.reasons||[result.reason]).map(reasonText).join(' '))}</div><div class="dialog-footer">${actionFor(event)}</div>`;
}
export function activityDetail(profile,id){
  const event=eventById(profile,id);
  if(!event)return `${dialogHead('Активность не найдена')}<p>Обновите каталог и попробуйте ещё раз.</p>`;
  const prediction=forecast(profile,id),person=profile.employee||{},roles=event.target_roles||[],grades=event.target_grades||[];
  return `${dialogHead(event.title||event.event_id)}<div class="dialog-body">${metadata(event)}<section class="detail-section"><h3>О мероприятии</h3><p class="event-description">${e(event.description||'Описание не добавлено в каталог.')}</p></section><section class="detail-section"><h3>Ожидаемый результат</h3>${prediction.available?forecastMetrics(prediction):`${effectList(event.gains||[])}<p class="muted">${e(reasonText(prediction.reason))}</p>`}</section><section class="detail-section"><h3>Условия участия</h3><ul class="requirements"><li>${icon(roles.includes(person.role)?'check-circle':'info')}<span>Роли: ${e(roles.join(', ')||'Не указаны')}</span></li><li>${icon(grades.includes(person.grade)?'check-circle':'info')}<span>Грейды: ${e(grades.join(', ')||'Не указаны')}</span></li>${(event.prerequisite_details||[]).map(skill=>`<li>${icon(profile.effective_skills&&skill.current>=skill.required?'check-circle':'alert-circle')}<span>${e(skill.name)}: нужен уровень ${n(skill.required)}${profile.effective_skills?', сейчас '+n(skill.current):''}</span></li>`).join('')}</ul>${!event.eligible&&event.reasons?.length?`<div class="info">${event.reasons.map(reason=>e(reasonText(reason))).join(' · ')}</div>`:''}</section>${event.upcoming_sessions?.length?`<section class="detail-section"><h3>Даты в каталоге</h3><p class="muted">${event.upcoming_sessions.map(session=>e(date(session))).join(' · ')}</p></section>`:''}</div><div class="dialog-footer"><button class="button secondary" data-action="forecast" data-id="${e(id)}">Что изменится</button>${actionFor(event)}</div>`;
}

export function skillDetail(profile,id){
  const skill=(profile.skills||[]).find(item=>item.skill_id===id),name=skill?.name||profile.skill_names?.[id]||id;
  const timeline=skillTimeline(profile,id),events=filterEvents(profile,{tab:'suitable',skills:[id]});
  return `${dialogHead(name)}<div class="dialog-body"><section class="skill-detail-level"><div><span class="muted">Текущий уровень</span><strong>${n(skill?.current??profile.effective_skills?.[id])}<small>/ 5</small></strong></div><div><span class="muted">Для цели</span><strong>${n(skill?.required)}<small>/ 5</small></strong></div>${levelDots(skill?.current??profile.effective_skills?.[id],skill?.required)}</section><section class="detail-section"><h3>Как менялся навык</h3><div class="timeline">${timeline.map(item=>`<article class="timeline-item"><span class="timeline-dot"></span><div><strong>${e(item.title)}</strong>${item.date?`<p class="muted">${e(date(item.date))}</p>`:''}${item.kind==='unavailable'?`<p class="muted">${e(reasonText(item.explanation))}</p>`:`<p>${known(item.before)?n(item.before)+' → ':''}${n(item.after)} ур.${known(item.gain)?' · '+delta(item.gain):''}</p>`}</div></article>`).join('')}</div><p class="explanation">История рассчитана по базовой оценке и текущему каталогу. Дата среза: ${e(date(profile.as_of_date))}.</p></section><section class="detail-section"><h3>Подходящие активности</h3>${events.length?`<div class="stack">${events.map(event=>`<article class="compact-activity"><h3>${e(event.title)}</h3><p class="muted">${e(label(event.format))} · ${n(event.duration_hours)} ч</p><button class="button text small" data-action="event" data-id="${e(event.event_id)}">Подробнее ${icon('arrow-right')}</button></article>`).join('')}</div>`:empty('Подходящих активностей нет','В текущем каталоге нет доступного шага для этого навыка.')}</section></div>`;
}
export function compareView(profile){
  const items=(profile.recommendations?.items||[]).filter(validRecommendation).slice(0,3);
  return `${dialogHead('Сравнить варианты','overlay-title','Выберите шаг, который подходит вам сейчас.')}<div class="dialog-body"><div class="compare-grid">${items.map(item=>{const result=forecast(profile,item.event_id),event=eventById(profile,item.event_id);return `<article class="compare-option"><h3>${e(item.title||item.event_id)}</h3>${metadata(item)}${result.available?forecastMetrics(result):effectList(item.gains||[])}<h3>Почему подходит</h3><ul class="factors">${item.factors.map(factor=>`<li>${icon('check-circle')}<span>${e(factor.text??factor)}</span></li>`).join('')}</ul>${actionFor(event)}</article>`;}).join('')||empty('Пока нечего сравнивать','Сначала подберите рекомендации на странице «Мой путь».')}</div></div>`;
}
export function completionView(result){
  return `<section class="completion-page"><div class="result-hero"><span class="completion-icon">${icon('check-circle')}</span><h1>${result.applied===false?'Выполнение уже учтено':'Активность завершена'}</h1>${result.title?`<p class="muted">${e(result.title)}</p>`:''}</div><section class="panel completion-result"><h2>Ваш прогресс</h2>${forecastMetrics(result)}${rewardFeedback(result.reward)}${unlocksView(result.unlocks)}</section><div class="form-actions completion-actions"><button class="button" data-action="next-step">Посмотреть следующий шаг ${icon('arrow-right')}</button><a class="button secondary" href="#home">Вернуться на «Мой путь»</a></div></section>`;
}
export function historyDetail(profile,id){
  const record=(profile.history||[]).find(row=>row.record_id===id),result=historyResult(profile,id);
  return `${dialogHead('Результат активности','detail-title',record?.title||record?.event_id||'')}<div class="dialog-body">${record?`<p class="muted">${e(date(record.date))} · ${e(label(record.status))}</p>`:''}${result.available?`<span class="pill neutral">${result.source==='reconstructed'?'Расчёт по текущей цели':'Сохранённый результат'}</span>${forecastMetrics(result)}${result.source==='reconstructed'?`<p class="explanation">${e(result.explanation)}</p>`:unlocksView(result.unlocks)}`:empty('Отдельный результат недоступен',reasonText(result.reason))}</div>`;
}
export function infoDialog(title,body,{html=false}={}){return `${dialogHead(title,'overlay-title')}<div class="dialog-body">${html?body:`<p>${e(body)}</p>`}</div><div class="dialog-footer"><button type="button" class="button secondary" data-action="close-dialog">Понятно</button></div>`;}
